project:
  type: website
  output-dir: docs

website:
  title: "Mukhammad Egamkulov"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - Experience.qmd
      - hobbies.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



